sudo: false # required
dist: trusty
language: cpp
compiler:
  - gcc
#  - clang
env:
global:
  - CTEST_OUTPUT_ON_FAILURE=1
matrix:
  - PROJECT=CPP_SANDBOX

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
#    - clang-3.8
    - cmake
    - cmake-data
    - libopenmpi-dev

before_install:
  - ./shallow-clone master https://github.com/boostorg/boost.git boost
#
#  - echo "using gcc : 4.9 ; " >> ~/build/rafald/cpp_sandbox/boost/tools/build/src/user-config.jam
#$ {:"echo \"using gcc"=>"4.9 ; \" >> ./boost/tools/build/src/user-config.jam"}
#/home/travis/build.sh: line 45: 4.9 ; " >> ./boost/tools/build/src/user-config.jam}: No such file or directory

# skips install
#install: true
#install: ./install-dependencies.sh
install: 

before_script:
  - ${CC} --version
  - pushd boost ; ./bootstrap.sh --with-toolset=gcc ; ls -lrt ; popd
  - bash -c "echo -n 'using gcc :' >> boost/tools/build/src/user-config.jam"
  - bash -c "echo -n ' :' >> boost/tools/build/src/user-config.jam"
  - bash -c "echo ' /usr/bin/gcc-5 ;' >> boost/tools/build/src/user-config.jam"
  - cat ~/build/rafald/cpp_sandbox/boost/tools/build/src/user-config.jam
  
script:
  - ${CC} --version
  - pwd ; ls -n boost ; touch Jamroot
  - BOOST_ROOT=./boost ./boost/bjam -d2 toolset=${CC}

after_success:
  - bash -c "echo 'RLD: SUCCESS'"

after_failure:
  - bash -c "echo 'RLD: failed\!'"
  