# Build matrix / environment variable are explained on:
# https://docs.travis-ci.com/user/languages/cpp/#C11-C%2B%2B11-(and-Beyond)-and-Toolchain-Versioning
# http://about.travis-ci.org/docs/user/build-configuration/
# This file can be validated on:
# http://lint.travis-ci.org/

#This job is running on container-based infrastructure, which does not allow use of 'sudo', setuid and setguid executables.
#If you require sudo, add 'sudo: required' to your .travis.yml
#See https://docs.travis-ci.com/user/workers/container-based-infrastructure/ for details.

branches:
  only:
    - master
    - develop

language: cpp

env:
  global:
  - CTEST_OUTPUT_ON_FAILURE=1

cache:
  ccache: true
  directories:
  - boost
  - EIGEN
  - GSL
  - $HOME/.ccache

# List of whitelisted in travis packages for ubuntu-trusty can be found here:
#   https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-trusty
# List of whitelisted in travis apt-sources:
#   https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json
matrix:
  fast_finish: true
  include:
    -
      os: osx
      osx_image: xcode9.1 # xcode8.3 xcode9
      #On OS X, the version of clang is controlled by the choice of osx_image.
      compiler: clang
      #$ clang --version
      #Apple LLVM version 9.0.0 (clang-900.0.38)
      sudo: false
    -
      os: linux
      compiler: clang
      env: CVER=5.0
      dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
           - clang-5.0
           - clang-format-5.0
           - clang-tidy-5.0
           - lcov
           - valgrind
           - cmake
           - cmake-data
           - libopenmpi-dev
           - gcovr
           - g++-7
    -
      os: linux
      compiler: gcc
      env: CVER=7
      dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
           - g++-7
           - clang-format-5.0
           - clang-tidy-5.0
           - lcov
           - valgrind
           - cmake
           - cmake-data
           - libopenmpi-dev
           - gcovr

before_install:

install:
  # install lcov to coveralls conversion + upload tool
  - gem install coveralls-lcov

before_script:
  - ./travis_shallow-clone-and-bootstrap master https://github.com/boostorg/boost.git boost ${CVER}

script:
  - if [ ! -f Jamroot ] ; then touch Jamroot ; fi
  - BOOST_ROOT=./boost ./boost/bjam -d2 -j8 toolset=${CC}


after_success:
  - "echo 'From .travis script: SUCCESS'"
  - clang-tidy-5.0 src/* # TODO does not work
  - BOOST_ROOT=./boost scan-build-5.0 ./boost/bjam -j8 toolset=${CC} variant=release
  # produce coveralls data
  - lcov --directory . --zerocounters
  - BOOST_ROOT=./boost ./boost/bjam -j8 toolset=${CC} variant=coverage
  - lcov --directory . --capture --output-file coverage.info # capture coverage info
  - lcov --remove coverage.info 'tests/*' '/usr/*' '/boost/*' '/EIGEN/*' --output-file coverage.info # filter out system and test code
  - lcov --list coverage.info # debug before upload
  - coveralls-lcov coverage.info # uploads to coveralls  # --repo-token ${COVERALLS_TOKEN}

after_failure:
  - bash -c "echo 'From .travis script: failed\!'"

notifications:
  email:
    on_success: change
    on_failure: change # always
