language: cpp

compiler:
#  - clang
  - gcc

env:
  global:
    - CTEST_OUTPUT_ON_FAILURE=1
  matrix:
    - PROJECT=BoostArray

before_install:
#  - sudo add-apt-repository -y ppa:purplekarrot/cmake
#  - sudo apt-get update
#  - sudo apt-get install cmake cmake-data libopenmpi-dev
#  - sudo apt-get install libboost-tools-dev 
#  - mkdir build
  - ./shallow-clone master https://github.com/boostorg/boost.git boost

script:
  - pushd boost
  - ./bootstrap.sh
  - popd 
  - clang --version
  - touch Jamroot
  - BOOST_ROOT=./boost ./boost/bjam -d2 toolset=${CC}
#  - cd build
#  - cmake -DCMAKE_BUILD_TYPE=Debug ..
#  - cmake --build . --target $PROJECT-test
