#This job is running on container-based infrastructure, which does not allow use of 'sudo', setuid and setguid executables.
#If you require sudo, add 'sudo: required' to your .travis.yml
#See https://docs.travis-ci.com/user/workers/container-based-infrastructure/ for details.

sudo: required # false
dist: trusty
language: cpp
cache:
  apt: true
  ccache: true
  directories:
  - boost
  - EIGEN
compiler:
  - gcc
#  - clang
env:
global:
  - CTEST_OUTPUT_ON_FAILURE=1
matrix:
  - PROJECT=CPP_SANDBOX

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-trusty
    - llvm-toolchain-trusty-3.8
    packages:
#    - clang-3.8
    - gcc-5
    - g++-5
    - cmake
    - cmake-data
    - libopenmpi-dev

before_install:
  - sudo apt-get remove gcc g++ -y
  - ./shallow-clone master https://github.com/boostorg/boost.git boost
#  - pwd ; ls -n ./boost/tools/build/src/ ./create_user-config 

install: 

before_script:
  - ${CC}-5 --version
  - pushd boost ; ./bootstrap.sh --with-toolset=${CC}-5 ; ./b2 headers ; ls -lrt ; popd
#  - cat ~/build/rafald/cpp_sandbox/boost/tools/build/src/user-config.jam
  
script:
  - ${CC}-5 --version
  - pwd ; ls -n boost ; touch Jamroot
  - BOOST_ROOT=./boost ./boost/bjam -d2 -j8 toolset=${CC}-5

after_success:
  - bash -c "echo 'RLD: SUCCESS'"

after_failure:
  - bash -c "echo 'RLD: failed\!'"
  