sudo: required
dist: trusty
language: cpp
compiler:
  - clang-3.9
  - gcc-5
env:
global:
  - CTEST_OUTPUT_ON_FAILURE=1
matrix:
  - PROJECT=CPP_SANDBOX

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
    - clang-3.9
    - cmake
    - cmake-data
    - libopenmpi-dev

before_install:
  - ./shallow-clone master https://github.com/boostorg/boost.git boost
#
#  - echo "using gcc : 4.9 ; " >> ~/build/rafald/cpp_sandbox/boost/tools/build/src/user-config.jam
#$ {:"echo \"using gcc"=>"4.9 ; \" >> ./boost/tools/build/src/user-config.jam"}
#/home/travis/build.sh: line 45: 4.9 ; " >> ./boost/tools/build/src/user-config.jam}: No such file or directory

# skips install
#install: true
#install: ./install-dependencies.sh
install: 

before_script:
  - ${CC} --version
  - pushd boost ; ./bootstrap.sh --with-toolset=gcc ; ls -lrt ; popd
  
script:
  - ${CC} --version
  - pwd ; ls -lrt boost ; touch Jamroot
  - bash -c 'echo "using gcc /usr/bin/gcc-5 ; " >> ~/build/rafald/cpp_sandbox/boost/tools/build/src/user-config.jam'
  - cat ~/build/rafald/cpp_sandbox/boost/tools/build/src/user-config.jam
  - BOOST_ROOT=./boost ./boost/bjam -d2 toolset=${CC}

after_success:
  - bash -c "echo 'RLD: SUCCESS'"

after_failure:
  - bash -c "echo 'RLD: failed\!'"
  