#This job is running on container-based infrastructure, which does not allow use of 'sudo', setuid and setguid executables.
#If you require sudo, add 'sudo: required' to your .travis.yml
#See https://docs.travis-ci.com/user/workers/container-based-infrastructure/ for details.

sudo: false # required
dist: trusty
language: cpp
cache:
  apt: true
  ccache: true
  directories:
  - boost
compiler:
  - gcc
#  - clang
env:
global:
  - CTEST_OUTPUT_ON_FAILURE=1
matrix:
  - PROJECT=CPP_SANDBOX

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
#    - clang-3.8
    - cmake
    - cmake-data
    - libopenmpi-dev

before_install:
  - ./shallow-clone master https://github.com/boostorg/boost.git boost
  - pwd ; ./create_user-config 

# skips install
#install: true
#install: ./install-dependencies.sh
install: 

before_script:
  - ${CC} --version
  - pushd boost ; ./bootstrap.sh --with-toolset=gcc ; ./b2 headers ; ls -lrt ; popd
  - cat ~/build/rafald/cpp_sandbox/boost/tools/build/src/user-config.jam
  
script:
  - ${CC} --version
  - pwd ; ls -n boost ; touch Jamroot
  - BOOST_ROOT=./boost ./boost/bjam -d2 toolset=${CC}

after_success:
  - bash -c "echo 'RLD: SUCCESS'"

after_failure:
  - bash -c "echo 'RLD: failed\!'"
  