sudo: required
dist: trusty
language: cpp
compiler:
#  - clang
#  - gcc-4.9
  - gcc
env:
global:
  - CTEST_OUTPUT_ON_FAILURE=1
matrix:
  - PROJECT=CPP_SANDBOX

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - ppa:purplekarrot/cmake
    packages:
    - g++-4.9
    - g++-6.1
    - cmake
    - cmake-data
    - libopenmpi-dev

before_install:
#  - sudo apt-get install libboost-tools-dev 
#  - mkdir build
  - ./shallow-clone master https://github.com/boostorg/boost.git boost
  - ls boost/tools/build/src
  - ls ~/build/rafald/cpp_sandbox/boost/tools/build/src
  - which gcc
#
#  - echo "using gcc : 4.9 ; " >> ~/build/rafald/cpp_sandbox/boost/tools/build/src/user-config.jam
#$ {:"echo \"using gcc"=>"4.9 ; \" >> ./boost/tools/build/src/user-config.jam"}
#/home/travis/build.sh: line 45: 4.9 ; " >> ./boost/tools/build/src/user-config.jam}: No such file or directory

#  - echo "using gcc : 4.4 : /usr/bin/g++-4.4 ; " >> tools/build/src/user-config.jam
#  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
#  - sudo apt-get update -q
#  - sudo apt-get install gcc-4.9 -y
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 20
  - sudo update-alternatives --config gcc
  - which gcc
#  - ~/build/rafald/cpp_sandbox/boost/bootstrap.sh --with-toolset=gcc-4.9

# skips install
#install: true
#install: ./install-dependencies.sh
install: 
  - ${CC} --version
  - cat ~/boost/tools/build/src/user-config.jam
  - ./boost/bootstrap.sh --with-toolset=gcc-4.9

before_script:

script:
  - ${CC} --version
  - touch Jamroot
  - BOOST_ROOT=./boost ./boost/bjam -d2 toolset=${CC}-4.9 
#  - cd build
#  - cmake -DCMAKE_BUILD_TYPE=Debug ..
#  - cmake --build . --target $PROJECT-test

after_success:
- echo "RLD: SUCCESS"

after_failure:
  - echo "RLD: failed!"
  