sudo: required
dist: trusty
language: cpp
compiler:
#  - clang-3.9
  - gcc-5
env:
global:
  - CTEST_OUTPUT_ON_FAILURE=1
matrix:
  - PROJECT=CPP_SANDBOX

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - ppa:purplekarrot/cmake
    packages:
    - g++-5 # libboost-tools-dev 
    - cmake
    - cmake-data
    - libopenmpi-dev

before_install:
  - ./shallow-clone master https://github.com/boostorg/boost.git boost
  - ls boost/tools/build/src
  - ls ~/build/rafald/cpp_sandbox/boost/tools/build/src
  - which gcc
#
#  - echo "using gcc : 4.9 ; " >> ~/build/rafald/cpp_sandbox/boost/tools/build/src/user-config.jam
#$ {:"echo \"using gcc"=>"4.9 ; \" >> ./boost/tools/build/src/user-config.jam"}
#/home/travis/build.sh: line 45: 4.9 ; " >> ./boost/tools/build/src/user-config.jam}: No such file or directory
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 20
  - sudo update-alternatives --config gcc
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 20
  - sudo update-alternatives --config g++
  - which g++

# skips install
#install: true
#install: ./install-dependencies.sh
install: 

before_script:
  - ${CC} --version
#  - bash -c 'echo "using gcc : : /usr/bin/gcc-5 ; " >> ~/build/rafald/cpp_sandbox/boost/tools/build/src/user-config.jam'
  - cat ~/build/rafald/cpp_sandbox/boost/tools/build/src/user-config.jam
  - pushd boost ; pwd ; ./bootstrap.sh --with-toolset=gcc ; popd
  - ls -lrt boost
  
script:
  - ${CC} --version
  - touch Jamroot
  - pwd
  - ls -lrt boost
  - BOOST_ROOT=./boost ./boost/b2 -d2 toolset=${CC}
#  - cd build
#  - cmake -DCMAKE_BUILD_TYPE=Debug ..
#  - cmake --build . --target $PROJECT-test

after_success:
  - bash -c "echo 'RLD: SUCCESS'"

after_failure:
  - bash -c "echo 'RLD: failed\!'"
  