#This job is running on container-based infrastructure, which does not allow use of 'sudo', setuid and setguid executables.
#If you require sudo, add 'sudo: required' to your .travis.yml
#See https://docs.travis-ci.com/user/workers/container-based-infrastructure/ for details.

sudo: required # false
dist: trusty
language: cpp
cache:
#  apt: true
  ccache: true
  directories:
  - boost
  - EIGEN
compiler:
  - gcc
  - clang
env:
global:
  - CTEST_OUTPUT_ON_FAILURE=1
matrix:
  - PROJECT=CPP_SANDBOX

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    - clang-3.6
    - cmake
    - cmake-data
    - libopenmpi-dev
    - gcovr
    - lcov

before_install:
#  - sudo apt-get remove gcc g++ -y # gcov is not available when this line is executed
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 20
  - sudo update-alternatives --config gcc  
  - ${CC} --version # gcc (Ubuntu 5.3.0-3ubuntu1~14.04) 5.3.0

install: #TODO CACHE IT
  # install lcov to coveralls conversion + upload tool
  - gem install coveralls-lcov

before_script:
  - ${CC} --version # gcc (Ubuntu 5.3.0-3ubuntu1~14.04) 5.3.0
  - git submodule init ; git submodule update --init --recursive 
  - ./travis_shallow-clone-and-bootstrap master https://github.com/boostorg/boost.git boost
  - ./travis_create_user-config g++-5 clang++-3.6 # configured gcc does not have any version - it is default
  
script:
#  - cd ${TRAVIS_BUILD_DIR}  
  - touch Jamroot
  - BOOST_ROOT=./boost ./boost/bjam -d2 -j8 toolset=${CC}

after_success:
  - "echo 'RLD: SUCCESS'"
#  - pushd ${TRAVIS_BUILD_DIR}
  - lcov --directory . --zerocounters
#  - cd ${TRAVIS_BUILD_DIR}
  - BOOST_ROOT=./boost ./boost/bjam -d2 -j8 toolset=${CC} variant=coverage
  - lcov --directory . --capture --output-file coverage.info # capture coverage info
  - lcov --remove coverage.info 'tests/*' '/usr/*' '/boost/*' '/EIGEN/*' --output-file coverage.info # filter out system and test code
  - lcov --list coverage.info # debug before upload
  - coveralls-lcov coverage.info # uploads to coveralls  # --repo-token ${COVERALLS_TOKEN}
#  - popd

after_failure:
  - bash -c "echo 'RLD: failed\!'"
  
