# Build matrix / environment variable are explained on:
# https://docs.travis-ci.com/user/languages/cpp/#C11-C%2B%2B11-(and-Beyond)-and-Toolchain-Versioning
# http://about.travis-ci.org/docs/user/build-configuration/
# This file can be validated on:
# http://lint.travis-ci.org/

#This job is running on container-based infrastructure, which does not allow use of 'sudo', setuid and setguid executables.
#If you require sudo, add 'sudo: required' to your .travis.yml
#See https://docs.travis-ci.com/user/workers/container-based-infrastructure/ for details.

branches:
  only:
    - master
    - develop

language: cpp
sudo: required
dist: trusty

env:
  global:
  - CTEST_OUTPUT_ON_FAILURE=1

cache:
  ccache: true
  directories:
  - boost
  - EIGEN
  - GSL
  - $HOME/.ccache

# List of whitelisted in travis packages for ubuntu-trusty can be found here:
#   https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-trusty
# List of whitelisted in travis apt-sources:
#   https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json
matrix:
  fast_finish: true
  include:
    -
      os: osx
      osx_image: xcode9.1
      #On OS X, the version of clang is controlled by the choice of osx_image.
      compiler: clang
      #$ clang --version
      #Apple LLVM version 9.0.0 (clang-900.0.38)
      sudo: false
    -
      os: osx
      osx_image: xcode9.1
      compiler: gcc #TODO
    -
      os: osx
      osx_image: xcode9
      compiler: clang
    -
      os: osx
      osx_image: xcode8.3
      compiler: clang

    - os: linux #compiler: clang
      addons:
        apt:
          sources:
            # llvm-toolchain-trusty-3.8 not accepted
            - llvm-toolchain-precise-3.8
            - ubuntu-toolchain-r-test
          packages:
            - clang-3.8
            - g++-5
            - llvm-dev
            - lcov
            - valgrind
            - cmake
            - cmake-data
            - libopenmpi-dev
            - gcovr
      env:
        - MATRIX_EVAL="CC=clang-3.8 && CXX=clang++-3.8"

    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-3.9
            - ubuntu-toolchain-r-test
          packages: [ "clang-3.9",
                      "g++-5",
                      "llvm-dev", "lcov", "valgrind", "cmake", "cmake-data", "libopenmpi-dev", "gcovr"]
      env:
        - MATRIX_EVAL="CC=clang-3.9 && CXX=clang++-3.9"

    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
            - ubuntu-toolchain-r-test
          packages: [ "clang-4.0",
                      "g++-5",
                      "llvm-dev", "lcov", "valgrind", "cmake", "cmake-data", "libopenmpi-dev", "gcovr"]
      env:
        - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"

    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
            - ubuntu-toolchain-r-test
          packages: [ "clang-5.0",
                      "g++-5",
                      "llvm-dev", "lcov", "valgrind", "cmake", "cmake-data", "libopenmpi-dev", "gcovr"]
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

    - os: linux #compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages: [ "g++-5",
                      "llvm-dev", "lcov", "valgrind", "cmake", "cmake-data", "libopenmpi-dev", "gcovr"]
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages: [ "g++-6",
                      "llvm-dev", "lcov", "valgrind", "cmake", "cmake-data", "libopenmpi-dev", "gcovr"]
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages: [ "g++-7",
                      "llvm-dev", "lcov", "valgrind", "cmake", "cmake-data", "libopenmpi-dev", "gcovr"]
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install: # ?why not    env: CC=gcc-6 CXX=g++-6
    - eval "${MATRIX_EVAL}"
install:
  # install lcov to coveralls conversion + upload tool
  - gem install coveralls-lcov

before_script:
  - ./travis_shallow-clone-and-bootstrap master https://github.com/boostorg/boost.git boost ${CC} #${CVER}

script:
  - if [ ! -f Jamroot ] ; then touch Jamroot ; fi
  - BOOST_ROOT=./boost ./boost/bjam -d2 -j8 toolset=${CC}


after_success:
  - "echo 'From .travis script: SUCCESS'"
  - clang-tidy src/*
  # TODO ^ does not work
  - BOOST_ROOT=./boost scan-build ./boost/bjam -j8 toolset=${CC} variant=release
  # produce coveralls data
  - lcov --directory . --zerocounters
  - BOOST_ROOT=./boost ./boost/bjam -j8 toolset=${CC} variant=coverage
  - lcov --directory . --capture --output-file coverage.info # capture coverage info
  - lcov --remove coverage.info 'tests/*' '/usr/*' '/boost/*' '/EIGEN/*' --output-file coverage.info # filter out system and test code
  - lcov --list coverage.info # debug before upload
  - coveralls-lcov coverage.info # uploads to coveralls  # --repo-token ${COVERALLS_TOKEN}

after_failure:
  - bash -c "echo 'From .travis script: failed\!'"

notifications:
  email:
    on_success: change
    on_failure: change # always
