sudo: required
dist: trusty

language: cpp

compiler:
#  - clang
  - gcc-4.9

env:
  global:
    - CTEST_OUTPUT_ON_FAILURE=1
  matrix:
    - PROJECT=BoostArray

before_install:
  - sudo add-apt-repository -y ppa:purplekarrot/cmake
#  - sudo apt-get update
#  - sudo apt-get install cmake cmake-data libopenmpi-dev
#  - sudo apt-get install libboost-tools-dev 
#  - mkdir build
  - ./shallow-clone master https://github.com/boostorg/boost.git boost
  - ls boost/tools/build/src
  - ls ~/build/rafald/cpp_sandbox/boost/tools/build/src
  - which gcc
#
  - ~/build/rafald/cpp_sandbox/bootstrap.sh --with-toolset=gcc
  - touch Jamroot
  - BOOST_ROOT=./boost ~/build/rafald/cpp_sandbox/boost/bjam -d2 toolset=${CC}-4.9 
#  - echo "using gcc : 4.9 ; " >> ~/build/rafald/cpp_sandbox/boost/tools/build/src/user-config.jam
#$ {:"echo \"using gcc"=>"4.9 ; \" >> ./boost/tools/build/src/user-config.jam"}
#/home/travis/build.sh: line 45: 4.9 ; " >> ./boost/tools/build/src/user-config.jam}: No such file or directory

#  - echo "using gcc : 4.4 : /usr/bin/g++-4.4 ; " >> tools/build/src/user-config.jam
#  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
#  - sudo apt-get update -q
#  - sudo apt-get install gcc-4.9 -y
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 20
  - sudo update-alternatives --config gcc

script:
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 20
  - sudo update-alternatives --config gcc
  - ${CC} --version
  - pushd boost
  - ./bootstrap.sh --with-toolset=gcc
  - popd 
  - touch Jamroot
  - BOOST_ROOT=./boost ./boost/bjam -d2 toolset=${CC}-4.9 
#  - cd build
#  - cmake -DCMAKE_BUILD_TYPE=Debug ..
#  - cmake --build . --target $PROJECT-test

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9

