#This job is running on container-based infrastructure, which does not allow use of 'sudo', setuid and setguid executables.
#If you require sudo, add 'sudo: required' to your .travis.yml
#See https://docs.travis-ci.com/user/workers/container-based-infrastructure/ for details.

sudo: required # false
dist: trusty
language: cpp
cache:
#  apt: true
  ccache: true
  directories:
  - boost
  - EIGEN
compiler:
  - gcc
  - clang
env:
global:
  - CTEST_OUTPUT_ON_FAILURE=1
matrix:
  - PROJECT=CPP_SANDBOX

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - clang-3.7
    - gcc-5
    - g++-5
    - cmake
    - cmake-data
    - libopenmpi-dev

before_install:
  - sudo apt-get remove gcc g++ -y
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 20
  - sudo update-alternatives --config gcc  
  - ${CC} --version # gcc (Ubuntu 5.3.0-3ubuntu1~14.04) 5.3.0 
  - ./shallow-clone master https://github.com/boostorg/boost.git boost
  - ./create_user-config 5 # configured gcc does not have any version - it is default
  
install: 

before_script:
  - pushd boost ; ./bootstrap.sh --with-toolset=${CC}
  - ./b2 headers # utility
#  - ./b2 chrono ; ./b2 system ; ./b2 unit_test_framework 
  - popd
  
script:
  - touch Jamroot
  - BOOST_ROOT=./boost ./boost/bjam -d2 -j8 toolset=${CC}

after_success:
  - bash -c "echo 'RLD: SUCCESS'"

after_failure:
  - bash -c "echo 'RLD: failed\!'"
  