#cache:
#  - packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
#  - projectA\libs
#  - node_modules                    # local npm modules
#  - '%APPDATA%\npm-cache'             # npm cache
#  - '%USERPROFILE%\.nuget\packages -> **\project.json'  # project.json cache

# https://www.appveyor.com/docs/appveyor-yml/

version: 1.0.{build}-{branch}

branches:
  only:
    - master
    - develop

image: Visual Studio 2017

# fetch repository as zip archive
shallow_clone: true                 # default is "false"

#   except:
#   - coverity_scan
environment:
  fast_finish: true
  matrix:
  - platform: x86
    os: Visual Studio 2017
    env: BS=bjam GENERATOR="MinGW Makefiles" MEMCHECK=DRMEMORY PLATFROM=x86
    configuration:  Release
    PROJECT_BASE: "C:/projects/cpp_sandbox"

install:
  #- C:\"Program Files (x86)"\"Microsoft Visual Studio 14.0"\VC\vcvarsall.bat %PLATFORM%
  - ps: cd "${env:APPVEYOR_BUILD_FOLDER}"
  - appveyor DownloadFile "https://dl.bintray.com/boostorg/beta/1.64.0.beta.2/source/boost_1_64_0_b2.7z"
  - ls -l && 7z x boost_*.7z > nul
  - del boost_*.7z > nul
  - cmd: cd "${env:APPVEYOR_BUILD_FOLDER}/boost*/"
  - cmd: call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
  - cmd: call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64
  - bootstrap.bat
  - b2 headers
  - set PATH=%PATH%;%CD% # TODO remove
  - set BOOST_ROOT=%CD% 
  - cmd: echo import boost ; > tools/build/src/user-config.jam
  - cmd: echo boost.use-project ; >> tools/build/src/user-config.jam
  #- cmd: echo using msvc ; >> tools/build/src/user-config.jam
  #- cmd: echo using python ; >> tools/build/src/user-config.jam
  - cat tools/build/src/user-config.jam
  - cmd: cd ..
  - hg clone https://bitbucket.org/eigen/eigen -r 3.2.8 EIGEN
  - git clone https://github.com/Microsoft/GSL.git GSL
  #- cinst drmemory
  #- appveyor DownloadFile http://downloads.sourceforge.net/mingw-w64/x86_64-5.2.0-release-posix-seh-rt_v4-rev1.7z
  #- 7z x x86_64-5.2.0-release-posix-seh-rt_v4-rev1.7z > nul
  - set PATH=%PATH%;mingw64\bin  
before_build:
  - ps: cd "${env:APPVEYOR_BUILD_FOLDER}"
  - cmd: copy /Y NUL Jamroot # ATTRIB -R filename.ext
build_script:
  - echo %CD% %PATH% %BOOST_ROOT%
  - bjam #toolset=msvc-14.0
#build:
#  parallel: true        # enable MSBuild parallel builds
#  project: "Script"     # path to Visual Studio solution or project
#  verbosity: detailed # quiet|minimal|normal|detailed

# to run your custom scripts instead of automatic tests
test_script:
  - echo This is my custom test script
# to disable automatic tests 
test: off
# run custom scripts before tests
before_test:
# run custom scripts after tests
after_test:
  
