#!/bin/bash
git clone --depth 1 --branch $1 $2 $3
cd $3
git submodule init

function clone_all_modules() {
for i in $(sed -n 's/\[submodule "\(.*\)"\]/\1/p' .gitmodules | sort); do
    spath=$(git config -f .gitmodules --get submodule.$i.path)
    surl=$(git config -f .gitmodules --get submodule.$i.url)
    git clone --depth 1 --branch $1 $surl $spath
done
}

git clone --depth 1 --branch $1 https://github.com/boostorg/config.git libs/config
git clone --depth 1 --branch $1 https://github.com/boostorg/chrono.git libs/chrono
git clone --depth 1 --branch $1 https://github.com/boostorg/system.git libs/system
git clone --depth 1 --branch $1 https://github.com/boostorg/test.git libs/test
git clone --depth 1 --branch $1 https://github.com/boostorg/timer.git libs/timer

git clone --depth 1 --branch $1 https://github.com/boostorg/build.git tools/build
git clone --depth 1 --branch $1 https://github.com/boostorg/inspect.git tools/inspect

#git submodule update

which gcc
echo "using gcc : 4.9 : /usr/bin/gcc-4.9 ; " >> tools/build/src/user-config.jam
