#!/bin/bash

set -e

function full_clone() {
#    for i in $(sed -n 's/\[submodule "\(.*\)"\]/\1/p' .gitmodules | sort); do
#        spath=$(git config -f .gitmodules --get submodule.$i.path)
#        surl=$(git config -f .gitmodules --get submodule.$i.url)
#        git clone --depth 1 --branch $1 $surl $spath
#    done
#    git submodule update
    git submodule update --init --recursive
}

function create_user_config() {
    # create brand new
    echo > ./boost/tools/build/src/user-config.jam

    # required by .travis.yml but normally in user_config.jam
    echo "import boost ;" >> ./boost/tools/build/src/user-config.jam
    echo "boost.use-project ;" >> ./boost/tools/build/src/user-config.jam

    echo "using gcc : : /usr/bin/${1} ;" >> ./boost/tools/build/src/user-config.jam
    echo "using clang : : /usr/bin/${2} ;" >> ./boost/tools/build/src/user-config.jam

    cat ./boost/tools/build/src/user-config.jam
}

function partial_clone() {
    for mod in chrono config function mpl ratio predef preprocessor smart_ptr system test throw_exception timer type_traits utility ;
    do
        git clone --depth 1 --branch $1 https://github.com/boostorg/${mod}.git libs/${mod}
    done
    
    git clone --depth 1 --branch $1 https://github.com/boostorg/build.git tools/build
    git clone --depth 1 --branch $1 https://github.com/boostorg/inspect.git tools/inspect
}

if [ ! -d ${3}/.git ] ; then
    git clone --depth 1 --branch $1 $2 $3
    pushd $3
    git submodule init
    full_clone $1
#    partial_clone $1
    
    echo ${CXX} ${CC} 
    create_user_config ${CC} ${CC}
    ./bootstrap.sh --with-toolset=${CC} ; ./b2 headers
    ./b2 variant=debug chrono ; ./b2 variant=debug system ; ./b2 variant=debug unit_test_framework 
    
    popd
else
    echo "$3 dir already present"
fi

if [ ! -d EIGEN/.hg ] ; then
    hg clone https://bitbucket.org/eigen/eigen EIGEN
fi
